[package]
name = "arcweight"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
authors = ["Your Name <your.email@example.com>"]
license = "MIT OR Apache-2.0"
description = "A high-performance, modular library for weighted finite state transducers"
readme = "README.md"
homepage = "https://github.com/yourusername/arcweight"
repository = "https://github.com/yourusername/arcweight"
keywords = ["fst", "transducer", "automata", "nlp", "speech"]
categories = ["algorithms", "data-structures", "science", "text-processing"]

[dependencies]
# core dependencies
thiserror = "1.0"
anyhow = "1.0"
num-traits = "0.2"
ordered-float = "4.2"
indexmap = "2.2"
rayon = { version = "1.8", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
bincode = { version = "1.3", optional = true }
byteorder = "1.5"
bitflags = "2.4"
rand = "0.8"

# development dependencies
[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.4"
pretty_assertions = "1.4"
approx = "0.5"

[features]
default = ["std", "parallel", "serde"]
std = []
parallel = ["rayon"]
serde = ["dep:serde", "bincode", "ordered-float/serde"]

[[bench]]
name = "benchmarks"
harness = false